data:
  H: 128
  W: 128

training:
  n_epochs: 1200
  batch_size: 100
  optimization:
    optimizer_name: Adam # which optimizer to use during training
    Adam:
      betas:
        - 0.9
        - 0.999
      lr: 0.002
    SGD:
      momentum: 0.9
      lr: 0.001

AE:
  D: 4 # dimensionality of the latent space
  N_latent_1: 400 # number of middle latent variables
  N_latent_2: 50
  