data:
  H: 200
  W: 200

training:
  n_epochs: 100
  batch_size: 64
  optimization:
    optimizer_name: Adam # which optimizer to use during training
    Adam:
      betas:
        - 0.9
        - 0.999
      lr: 0.001
    SGD:
      momentum: 0.9
      lr: 0.001

AE:
  D: 128 # dimensionality of the latent space
