data:
  H: 200
  W: 200

training:
  n_epochs: 1200
  batch_size: 100
  optimization:
    optimizer_name: Adam # which optimizer to use during training
    Adam:
      betas:
        - 0.9
        - 0.999
      lr: 0.002
    SGD:
      momentum: 0.9
      lr: 0.001

AE:
  D: 100 # dimensionality of the latent space
